### ISSUE TITLE
Non-SRD content

### ISSUE THREAD

**Issue by bgior** [vorpalhex/srd_spells#12]
I would like to use this data for a project, but I'm concerned about the licensing. The readme says: 

> ...contains content from the SRD and is restricted and covered by the OGL

However, there are some spells that are apparently non-SRD, like "Ice Knife", which as far as I know is part of EEPC and not released under OGL. Could we get any clarification about whether _all_ of the content in `spells.json` was taken from SRD and can be safely used under OGL?

**Comment by vorpalhex** [comment]
We do our best to keep all content compliant and respond to notifications in a timely manner, but this is a project done by several people in their spare time, and so it's up to you to make sure your usage of any materials is compliant. We neither carry nor offer any liability in this regard.

**Comment by bgior** [comment]
Okay. I didn't mean it as request for legal advice, of course, I just wanted be sure that the SRD was the source of this data. I ended up using a heavily [modified version](https://github.com/bgior/weavelore/blob/master/public/srd.json), deleting 77 spells that weren't on the SRD 5.1 and adding 17 that were missing. For the benefit of anybody interested, here's the list:

```
-Absorb Elements
+Acid Arrow
-Arcane Gate
+Arcane Hand
+Arcane Sword
+Arcanist’s Magic Aura
-Aura Of Vitality
-Aura of Life
-Aura of Purity
-Banishing Smite
-Beast Bond
-Beast Sense
+Black Tentacles
-Blade Ward
-Blinding Smite
-Bones of the Earth
-Catapult
-Chromatic Orb
-Circle of Power
-Cloud of Daggers
-Compelled Duel
-Conjure Barrage
-Conjure Volley
-Control Flames
-Control Winds
-Cordon Of Arrows
-Create Bonfire
-Crown of Madness
-Crusader's Mantle
-Destructive Wave
-Dissonant Whispers
-Dust Devil
-Earth Tremor
-Earthbind
-Elemental Bane
-Elemental Weapon
-Ensnaring Strike
-Erupting Earth
+Faithful Hound
-Feign Death
-Flame Arrows
+Floating Disk
+Freezing Sphere
-Friends
-Frostbite
-Grasping Vine
-Gust
-Hail of Thorns
-Hex
+Hideous Laughter
-Ice Knife
-Immolation
+Instant Summons
-Investiture of Flame
-Investiture of Ice
-Investiture of Stone
-Investiture of Wind
+Irresistible Dance
-Lightning Arrow
-Maelstrom
-Magic Stone
+Magnificent Mansion
-Mold Earth
-Phantasmal Force
-Power Word Heal
-Primordial Ward
+Private Sanctum
-Pyrotechnics
-Ray of Sickness
+Resilient Sphere
+Secret Chest
-Searing Smite
-Shape Water
-Skywrite
-Staggering Smite
-Storm Sphere
-Swift Quiver
-Telepathy
+Telepathic Bond
-Thorn Whip
-Thunderclap
-Thunderous Smite
-Tidal Wave
+Tiny Hut
-Transmute Rock
-Tsunami
-Vitriolic Sphere
-Wall of Sand
-Wall of Water
-Warding Wind
-Watery Sphere
-Whirlwind
-Witch Bolt
-Wrathful Smite
```
