### ISSUE TITLE
Informing of attribution

### ISSUE THREAD

**Issue by sesopenko** [vorpalhex/srd_spells#3]
Hi I just wanted to let you know that I'm using your JSON file for my own project.  I've attributed the usage here: http://tools.fromthetabletop.net/#/spells

The project itself is also open source at https://github.com/sesopenko/dndnext-sheet

Thanks for going through the trouble to parse the SRD document.  The MD markup in the description is great!

**Comment by vorpalhex** [comment]
Thanks so much! I'm going to leave this open until I get a chance to add a section to the readme of project users.

**Comment by vorpalhex** [comment]
Added!
